#**Numpy**



## Ceating array

In [ ]:
import numpy as np

arr=np.array(5)  #0d array
print(arr)
print(arr.ndim)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.ndim)

5
0
2


In [ ]:
a=[[5,6,7,8,9],[2,3,4,5,6]]
b=np.array(a)
print(b,"\n shape is",b.shape,"\n size is ",b.size,"\n dim is ",b.ndim ,"\n type",b.dtype)

[[5 6 7 8 9]
 [2 3 4 5 6]] 
 shape is (2, 5) 
 size is  10 
 dim is  2 
 type int64


## Accessing array index

In [ ]:
arr=np.array([1,2,3])
print(arr[0:2])

arr1=np.array([[1,2,3],[4,5,7]])
print(arr1[1,1])

arr1[1,1]=9
print(arr1)
print(arr1[1,1])
print(arr[2]+arr1[1,2])

[1 2]
5
[[1 2 3]
 [4 9 7]]
9
10


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(a[1,1,1])
print(a[1,1,-1])  #negative indexing


3
11
12


##Slicing array


In [ ]:
# a=np.array([1,2,3,4,5,6,7])
# print(a[1])
# print(a[0:4]) #start:end
# print(a[0:5:3]) #start:end:step


b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b[1,0:3])

[7 8 9]


## CW

In [ ]:
b = [7, 14, 21, 28]
a = np.array(b)
print(a)

[ 7 14 21 28]


In [ ]:
a = np.array([[5, 10, 15], [20, 25, 30]])
print(f"shape is {a.shape}, dimension is {a.ndim}")

shape is (2, 3), dimension is 2


In [ ]:
zro = np.zeros((2, 3))
rng = np.arange(13)
print(zro, "\n\n", rng[0:13:3])

[[0. 0. 0.]
 [0. 0. 0.]] 

 [ 0  3  6  9 12]


In [ ]:
a=np.array([2,4,6,8])
print(a*3)

[ 6 12 18 24]


In [ ]:
b=np.array([1,3,5,7,9,11])
print(b[2])
print(b[1:3])

5
[3 5]
