#***LINEAR ALGEBRA***

##SCALAR AND VECTOR

In [4]:
import numpy as np

scalar=12

vector=np.array([1,2,3,4])

scaled_vector=scalar*vector

print("Scalar:",scalar,"\nVector:",vector,"\nScaled_Vector:",scaled_vector)


Scalar: 12 
Vector: [1 2 3 4] 
Scaled_Vector: [12 24 36 48]


In [6]:
vctr=np.array([4,5,6])
print(3*vctr)

[12 15 18]


##VECTOR OPERATION

In [7]:
import numpy as np

v1=np.array([1,2,3])
v2=np.array([4,5,6])

print(v1+v2)
print(v1-v2)

[5 7 9]
[-3 -3 -3]


In [8]:
v1=np.array([10,20])
v2=np.array([5,15])

print(v1+v2)
print(v1-v2)

[15 35]
[5 5]


##Matrix Creation and Basic Operations

###basic operation

In [37]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])

print(m1,"\n\n",m2,"\n")
print(m1+m2,"\n")
print(m1-m2,"\n")
print(np.dot(m1,m2),"\n")
print(m1*m1)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[19 22]
 [43 50]] 

[[ 1  4]
 [ 9 16]]


###3*3 Matrix


In [35]:
m1=np.array([[[1,2,3],[4,5,6],[1,2,3]]])
m2=np.array([[[1,2,3],[2,1,2],[1,2,3]]])

dot=np.dot(m1,m2)
print(dot)

[[[[ 8 10 16]]

  [[20 25 40]]

  [[ 8 10 16]]]]


###Matrix multipliaction scratch

In [50]:
m1=np.array([[1,2],[2,3]])
m2=np.array([[1,2],[2,3]])

i1=(m1[0,0]*m2[0,0])+(m1[0,1]*m2[0,1])
i2=(m1[0,0]*m2[1,0])+(m1[0,1]*m2[1,1])
i3=(m1[1,0]*m2[0,0])+(m1[1,1]*m2[0,1])
i4=(m1[1,0]*m2[1,0])+(m1[1,1]*m2[1,1])

print(i1,"\t",i2,"\n",i3,"\t",i4)
print(np.dot(m1,m2))


5 	 8 
 8 	 13
[[ 5  8]
 [ 8 13]]


###Identity and transpose

In [58]:
identity=np.eye(3,dtype=int)
print(identity)

m1=np.array([[1,2,3],[4,5,6]])
print(m1,"\n\n",m1.T)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 3]
 [4 5 6]] 

 [[1 4]
 [2 5]
 [3 6]]


###Transpose from scratch

In [68]:
a=np.array([[1,2],[3,4]])
print(a.T,"\n\n")

b=a[0,1]
c=a[1,0]
a[1,0]=b
a[0,1]=c
print(a)

[[1 3]
 [2 4]] 


[[1 3]
 [2 4]]


###Matrix Inverse

In [81]:
m1=np.array([[1,2],[3,4]])
i=np.linalg.inv(m1)

m3=np.dot(m1,i)
print(np.round(m3))

[[1. 0.]
 [0. 1.]]
